### ISSUE TITLE
Allow sprintf for topic_id

### ISSUE THREAD

**Issue by justinsteffy** [joekiller/logstash-kafka#19]
Allowing the logstash `sprintf` call on the `topic_id` would allow routing events to different topics without multiple conditionals and producers.  

In my use case, I'd like to send events on a few different topics (e.g. Logs.System, Logs.App, Metrics.App...).  With `sprintf` on the event, I could tag each `input` with a `type` and use that to dispatch to a matching `topic`.

Does this sound feasible?

**Comment by joekiller** [comment]
@justinsteffy check out https://github.com/logstash-plugins/logstash-output-kafka/pull/9

**Comment by justinsteffy** [comment]
@joekiller thanks for the heads up.  I'll go ahead and close this issue.
