### ISSUE TITLE
Feature request: Access to kafka keys in input

### ISSUE THREAD

**Issue by jpodeszwik** [joekiller/logstash-kafka#38]
In my company we're using kafka keys to store some metadata like timestamp, etc. We need access to kafka keys in logstash.

I can add those changes myself and make pull requests, but first I need to have some kind of "green light".

Adding that will also require changes in jruby-kafka in Consumer class. We should put some kind of objects to queue instead of strings - that may not be backwards compatible. Should I add another option to juruby-kafka library and give client ability to choose if he wants to receive full objects or just string messages?

**Comment by joekiller** [comment]
@jpodeszwik I've implemented this on master.  (https://github.com/joekiller/logstash-kafka/blob/master/lib/logstash/inputs/kafka.rb#L156).  Take a look.

**Comment by joekiller** [comment]
https://github.com/joekiller/logstash-kafka/commit/f874eb498bbedfd9594a4a07f0ac14c016c32809

**Comment by jpodeszwik** [comment]
@joekiller Didn't have time to look deeper, but it seems fine. Thanx!
