### ISSUE TITLE
Kafka Producers Throws Exception

### ISSUE THREAD

**Issue by viveksofty** [joekiller/logstash-kafka#45]
Hello 

I have Configured Manual install of our log stash-kafka

My Logstash Configuration is running ., But it throws Following Exception as

"kafka producer threw exception, restarting {:exception=>java.lang.ClassCastException: java.lang.String cannot be cast to [B, :level=>:warn}"

I'm not able to configure using "make tar ball"

Could help me to figure out my issue :)
And also there is no example case of kakfa input & kafka output case just parameters explained .,
Please help me to figure out the issues as soon as possible
Thanks :)

**Comment by joekiller** [comment]
This sounds similar to issue #28.  The fix was unclear but it was reported
that he ran make tarball and then adjusted his outputs config.  Could you
please post your config?

**Comment by joekiller** [comment]
Hi,

I've revamped the manual install for the plugin and it is much more failsafe now.  Please reinstall logstash and then try https://github.com/joekiller/logstash-kafka#rubygems-logstash-kafka-install

It is probably best if you rm -rf /opt/logstash after you yum remove logstash or apt-get remove logstash, etc.
