### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by MaheshSankaran** [joekiller/logstash-kafka#47]
[user@host logstash-kafka]$ make tarball
echo "VERSION=1.4.2" >> .VERSION.mk
=> Fetching logstash 1.4.2
=> Extracting build/tarball/logstash-1.4.2.tar.gz
=> Downloading jruby 1.7.11
=> Ensuring ruby gems dependencies are in vendor/bundle...
Error: Invalid or corrupt jarfile vendor/jar/jruby-complete-1.7.11.jar
make: *** [vendor/bundle] Error 1

**Comment by joekiller** [comment]
I'll take a look at this

**Comment by MaheshSankaran** [comment]
Thank you for your quick reply joe.

**Comment by joekiller** [comment]
I'm not sure what the problem is, perhaps a repo outage?  Try `git clean
-xfd` and build again

**Comment by MaheshSankaran** [comment]
Hi joe,
git clean not working.still it shows error.

[user@host logstash-kafka]$ git clean -xfd
Removing .VERSION.mk
Removing build/
Removing vendor/
[user@host logstash-kafka]$ make tarball
echo "VERSION=1.4.2" >> .VERSION.mk
=> Fetching logstash 1.4.2
=> Extracting build/tarball/logstash-1.4.2.tar.gz
=> Downloading jruby 1.7.11
=> Ensuring ruby gems dependencies are in vendor/bundle...
Error: Invalid or corrupt jarfile vendor/jar/jruby-complete-1.7.11.jar
make: *** [vendor/bundle] Error 1

**Comment by MaheshSankaran** [comment]
Hi joe,now it is working fine.

thanks

**Comment by joekiller** [comment]
Yay! glad to help. (close #47)

**Comment by joekiller** [comment]
Well that close didn't work. Manually closing.
