### ISSUE TITLE
plugin not working against 1.5.0.beta1

### ISSUE THREAD

**Issue by Analect** [joekiller/logstash-kafka#52]
@joekiller 
I downloaded the logstash.1.5.0.beta.tar.gz, and ran 'rake bootstrap', as per https://logstash.jira.com/browse/LOGSTASH-1839
This went through a series of installs and their dependencies.
I then attempted to install the kafka-logstash plugin, as per your readme, but that failed.

me@ubuntu-1404:~/Development/Tools/Eolas/logstash-1.5.0.beta1$ bin/plugin install logstash-kafka
validating logstash-kafka >= 0
Invalid logstash plugin gem 'logstash-kafka'. Aborting...

I then tried 'gem install logstash-kafka', but that also failed ... and suggested that I try 'logstash-input-kafka', which also failed (see below). 

Any pointers on where I might be going wrong here?
Thanks,
Colum

me@ubuntu-1404:~/Development/Tools/Eolas/logstash-1.5.0.beta1$ gem install logstash-kafka
ERROR:  Could not find a valid gem 'logstash-kafka' (>= 0) in any repository
ERROR:  Possible alternatives: logstash-fakes, logstash_rails, logstash-lib, logstash-file, logstash-input-kafka
me@ubuntu-1404:~/Development/Tools/Eolas/logstash-1.5.0.beta1$ bin/plugin install logstash-input-kafka
validating logstash-input-kafka >= 0
Valid logstash plugin. Continuing...
Gem::UnsatisfiableDependencyError: Unable to resolve dependency: logstash-input-kafka (= 0.1.11) requires logstash-core (< 2.0.0, >= 1.4.0)
           resolve_for at /home/me/Development/Tools/Eolas/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rubygems/dependency_resolver.rb:144
           resolve_for at /home/me/Development/Tools/Eolas/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rubygems/dependency_resolver.rb:194
               resolve at /home/me/Development/Tools/Eolas/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rubygems/dependency_resolver.rb:87
               resolve at /home/me/Development/Tools/Eolas/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rubygems/request_set.rb:134
  resolve_dependencies at /home/me/Development/Tools/Eolas/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rubygems/dependency_installer.rb:408
               install at /home/me/Development/Tools/Eolas/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rubygems/dependency_installer.rb:345
               execute at /home/me/Development/Tools/Eolas/logstash-1.5.0.beta1/lib/logstash/pluginmanager/install.rb:60
                   run at /home/me/Development/Tools/Eolas/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/clamp-0.6.4/lib/clamp/command.rb:67
               execute at /home/me/Development/Tools/Eolas/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/clamp-0.6.4/lib/clamp/subcommand/execution.rb:11
                   run at /home/me/Development/Tools/Eolas/logstash-1.5.0.beta1/lib/logstash/runner.rb:144
                  call at org/jruby/RubyProc.java:271
                   run at /home/me/Development/Tools/Eolas/logstash-1.5.0.beta1/lib/logstash/runner.rb:171
                  call at org/jruby/RubyProc.java:271
            initialize at /home/me/Development/Tools/Eolas/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/task.rb:12

**Comment by joekiller** [comment]
I wouldn't use the 1.5 plugin for production until 1.5 is out of beta.  That being said I think the plugins are functional for the latest beta, 1.5rc2 or 3 now. I've updated this repo to work on logstash 1.4.X+ which had been broken for a while. I don't have the latest gem pushes but building from master should work.

**Comment by Analect** [comment]
Thanks Joe. From recollection, I think I was able to get it working against the RC1.
